---
- name: Install and Start Apache on EC2
  hosts: all
  become: yes

  tasks:

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Apache2 package
      apt:
        name: apache2
        state: present

    - name: Ensure Apache service is started
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Deploy a simple webpage
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Terraform + Ansible Automation Successful!</h1>"
